/* tslint:disable */
// This file is generated
// Do not edit this file
import * as createBucket from "./createBucket/index";
export * as createBucket from "./createBucket/index";
import * as deleteBucket from "./deleteBucket/index";
export * as deleteBucket from "./deleteBucket/index";
import * as copyObject from "./copyObject/index";
export * as copyObject from "./copyObject/index";
import * as deleteBucketPolicy from "./deleteBucketPolicy/index";
export * as deleteBucketPolicy from "./deleteBucketPolicy/index";
import * as deleteBucketWebsite from "./deleteBucketWebsite/index";
export * as deleteBucketWebsite from "./deleteBucketWebsite/index";
import * as deleteObject from "./deleteObject/index";
export * as deleteObject from "./deleteObject/index";
import * as deleteObjects from "./deleteObjects/index";
export * as deleteObjects from "./deleteObjects/index";
import * as getObject from "./getObject/index";
export * as getObject from "./getObject/index";
import * as listObjectsV2 from "./listObjectsV2/index";
export * as listObjectsV2 from "./listObjectsV2/index";
import * as putObject from "./putObject/index";
export * as putObject from "./putObject/index";
import * as listBuckets from "./listBuckets/index";
export * as listBuckets from "./listBuckets/index";

export type Actions = {
  createBucket: createBucket.ActionCreateBucket;
  deleteBucket: deleteBucket.ActionDeleteBucket;
  copyObject: copyObject.ActionCopyObject;
  deleteBucketPolicy: deleteBucketPolicy.ActionDeleteBucketPolicy;
  deleteBucketWebsite: deleteBucketWebsite.ActionDeleteBucketWebsite;
  deleteObject: deleteObject.ActionDeleteObject;
  deleteObjects: deleteObjects.ActionDeleteObjects;
  getObject: getObject.ActionGetObject;
  listObjectsV2: listObjectsV2.ActionListObjectsV2;
  putObject: putObject.ActionPutObject;
  listBuckets: listBuckets.ActionListBuckets;
}
