/* tslint:disable */
// This file is generated
// Do not edit this file
import * as createBucket from "./createBucket/index";
export * as createBucket from "./createBucket/index";
import * as deleteBucket from "./deleteBucket/index";
export * as deleteBucket from "./deleteBucket/index";
import * as copyObject from "./copyObject/index";
export * as copyObject from "./copyObject/index";
import * as deleteBucketPolicy from "./deleteBucketPolicy/index";
export * as deleteBucketPolicy from "./deleteBucketPolicy/index";
import * as deleteBucketWebsite from "./deleteBucketWebsite/index";
export * as deleteBucketWebsite from "./deleteBucketWebsite/index";
import * as deleteObject from "./deleteObject/index";
export * as deleteObject from "./deleteObject/index";
import * as deleteObjects from "./deleteObjects/index";
export * as deleteObjects from "./deleteObjects/index";
import * as getObject from "./getObject/index";
export * as getObject from "./getObject/index";
import * as listObjectsV2 from "./listObjectsV2/index";
export * as listObjectsV2 from "./listObjectsV2/index";
import * as putObject from "./putObject/index";
export * as putObject from "./putObject/index";
import * as listBuckets from "./listBuckets/index";
export * as listBuckets from "./listBuckets/index";

export type Actions = {
  "createBucket": createBucket.CreateBucket;
  "deleteBucket": deleteBucket.DeleteBucket;
  "copyObject": copyObject.CopyObject;
  "deleteBucketPolicy": deleteBucketPolicy.DeleteBucketPolicy;
  "deleteBucketWebsite": deleteBucketWebsite.DeleteBucketWebsite;
  "deleteObject": deleteObject.DeleteObject;
  "deleteObjects": deleteObjects.DeleteObjects;
  "getObject": getObject.GetObject;
  "listObjectsV2": listObjectsV2.ListObjectsV2;
  "putObject": putObject.PutObject;
  "listBuckets": listBuckets.ListBuckets;
}
