/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Input {
  /**
   * The source bucket name where the object is stored.
   */
  sourceBucket: string;
  /**
   * The key/name of the source object.
   */
  sourceKey: string;
  /**
   * The destination bucket name where the object will be copied to.
   */
  destinationBucket: string;
  /**
   * The key/name for the object in the destination bucket.
   */
  destinationKey: string;
}
