/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Input {
  /**
   * The name of the bucket that will be created.
   */
  bucketName: string;
  /**
   * The region where the bucket will exist (default is us-east-1).
   */
  region: string;
}
